---
title: "Output: Practical 1"
output: html_document
---

```{r}

rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(pacman)
p_load(fmxdat,tidyverse, rmsfuns, tbl2xts, PerformanceAnalytics, xts, glue, lubridate)

```


# Data loading

Loading in Jalshtr dataset from the fmxdat library.

```{r}

dta <- fmxdat::Jalshtr
```
Checking missing values

```{r}
sum(is.na(dta$TRI)) #=0... no missing TRI values
sum(is.na(dta$date)) #=0... no missing dates

```


# Cumulative Returns Since Inception
```{r, warning=FALSE}
# Calculating Simple Returns

dta2 <- dta %>% arrange(date) %>%
    mutate(across(.cols = TRI, .fns = ~./lag(.) - 1, .names = "Simple_Returns"))%>%
# Specifying that the first date should be excluded (avoid NA's)
    filter(date>first(date))%>%
# Calculating cumulative returns
    mutate(Cum_Ret = cumprod(1 + Simple_Returns))

# calculating cumulative returns for different bps levels
# (100 bps approximately 1%)

dta22 <- dta2 %>%
  arrange(date) %>%
  mutate(bps_10=(Cum_Ret*0.999))%>%
  mutate(bps_50=(Cum_Ret*0.995))%>%
  mutate(bps_100=(Cum_Ret*0.99))%>%
  mutate(bps_200=(Cum_Ret*0.98))%>%
  mutate(bps_250=(Cum_Ret*0.975))%>%
  mutate(bps_350=(Cum_Ret*0.965))

# In order to create legend (ie by type), need to collect the bps columns into a single one (pivot longer)

dta221 <- dta22 %>%
  arrange(date)%>%
  pivot_longer(cols=starts_with("bps"), 
               names_to="Type",
               values_to="Tyranny" )
  
p1<-
    ggplot(dta221) + 
geom_line(aes(date, Tyranny, colour=Type)) + 
fmxdat::theme_fmx(title.size = ggpts(30), 
                    subtitle.size = ggpts(28),
                    caption.size = ggpts(25),
                    CustomCaption = T,
                  legend.size = 10,
                  legend.pos = "right") + 
    fmxdat::fmx_cols() + 
  
  labs(x = "", y = "Cumulative Returns", caption = "Note:\nOwn Calculations",
       title = "Cumulative Returns Since Inception",
       subtitle = "Base Return: FTSE JSE ALSI \nStart: June 2002")

```


# Cumulative Returns since 2010
```{r, warning=FALSE}
dta3 <- dta221%>%filter(date>lubridate::ymd(20100101))

p<-
    ggplot(dta3) + 
geom_line(aes(date, Tyranny, colour=Type)) + 
fmxdat::theme_fmx(title.size = ggpts(30), 
                    subtitle.size = ggpts(28),
                    caption.size = ggpts(25),
                    CustomCaption = T,
                  legend.size = 10,
                  legend.pos = "right") + 
    fmxdat::fmx_cols() + 
  
  labs(x = "", y = "Cumulative Returns", caption = "Note:\nOwn Calculations",
       title = "Cumulative Returns Since 2010",
       subtitle = "Base Return: FTSE JSE ALSI \nStart: January 2010")

```
